# Generated by Django 2.2.2 on 2019-07-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_auto_20190714_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='web_site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
