# Generated by Django 2.2.2 on 2019-09-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190915_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='authors_books', to='books.Author', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='categories_books', to='categories.Category', verbose_name='Categories'),
        ),
    ]
